import{a as m,S as L,i}from"./assets/vendor-C1DvvBV_.js";(function(){const a=document.createElement("link").relList;if(a&&a.supports&&a.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))f(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const d of o.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&f(d)}).observe(document,{childList:!0,subtree:!0});function r(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function f(e){if(e.ep)return;e.ep=!0;const o=r(e);fetch(e.href,o)}})();m.defaults.baseURL="https://pixabay.com/api/";async function y(t,a){return(await m.get("/",{params:{q:t,page:a,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,key:"57805078-134aca3c8ad054738ba6853d0"}})).data}const s={form:document.querySelector(".search-form"),gallery:document.querySelector(".gallery"),loadMore:document.querySelector(".load-more"),loader:document.querySelector(".loader")},b=new L(".gallery a");function g(t){const a=t.map(r=>`
        <li class="gallery-item">
          <a class="gallery-link" href="${r.largeImageURL}">
            <img
              class="gallery-image"
              src="${r.webformatURL}"
              alt="${r.tags}"
            />
          </a>
        </li>
      `).join("");s.gallery.insertAdjacentHTML("beforeend",a),b.refresh()}function w(){s.gallery.innerHTML=""}function h(){s.loader.classList.remove("is-hidden")}function p(){s.loader.classList.add("is-hidden")}function u(){s.loadMore.classList.remove("is-hidden")}function c(){s.loadMore.classList.add("is-hidden")}let n=1,l="";s.form.addEventListener("submit",S);s.loadMore.addEventListener("click",M);async function S(t){if(t.preventDefault(),l=new FormData(t.currentTarget).get("search-text").trim(),!!l){n=1,w(),c(),h();try{const r=await y(l,n);if(r.hits.length===0){i.error({message:"Sorry, there are no images matching your search query. Please try again!"});return}g(r.hits),n*15>=r.totalHits?(c(),i.info({message:"We're sorry, but you've reached the end of search results."})):u()}catch{i.error({message:"Something went wrong. Please try again."})}finally{p()}}}async function M(){n+=1,c(),h();try{const t=await y(l,n);g(t.hits);const r=s.gallery.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"}),n*15>=t.totalHits?(c(),i.info({message:"We're sorry, but you've reached the end of search results."})):u()}catch{n-=1,i.error({message:"Something went wrong. Please try again."}),u()}finally{p()}}
//# sourceMappingURL=index.js.map
